mainSections = ["docs"]
description = "Software development, molecular biology, graphics programming, and messing about with Claude Code."
author = "Jim Andreas"
github = "https://github.com/jimandreas"
twitterCardEnabled = true
twitterCardSite = "jim__andreas"
twitterCreator = "jim__andreas"

# 404 page
notFoundHeader = "Page Not Found"
notFoundText = "Sorry, the page you're looking for doesn't exist."
